---

resource_types:
  - name: hashicorp-release
    type: docker-image
    source:
      repository: harbor.ci.gstack.io/starkandwayne/hashicorp-release-resource
      username: ((docker_registry_username))
      password: ((docker-registry-password))

resources:
  - name: gk-ops-image
    type: docker-image
    icon: docker
    source:
      repository: harbor.ci.gstack.io/gstack/gk-ops
      username: ((docker_registry_username))
      password: ((docker-registry-password))

  - name: consul-zip-release
    type: hashicorp-release
    source:
      project: consul

  - name: gk-automation
    type: git
    icon: github
    source:
      uri: git@github.com:gstackio/gk-automation.git
      branch: master
      private_key: ((github-private-key))

  - name: bpm-bosh-io-release
    type: bosh-io-release
    source:
      repository: cloudfoundry/bpm-release

  - name: consul-boshrelease-master
    type: git
    icon: github
    source:
      uri: ((consul_release_git_uri))
      branch: master
      private_key: ((github-private-key))

jobs:
  - name: detect-consul
    serial: true
    plan:
      - in_parallel:
          - get: consul-zip-release
            trigger: true
            params: { regexp: linux_amd64.zip }
          - get: consul-boshrelease-master
          - get: gk-automation
          - get: gk-ops-image

      - task: checkout-branch
        image: gk-ops-image
        file: gk-automation/tasks/git/checkout-branch.yml
        input_mapping:
          artifact-version: consul-zip-release
          repo:             consul-boshrelease-master
        params:
          BASE_BRANCH:          master
          BRANCH_NAME_TEMPLATE: bump-consul-${artifact_version}
          GITHUB_PRIVATE_KEY:   ((github-private-key))

      - task: bump-blob
        image: gk-ops-image
        file: gk-automation/tasks/boshrelease/bump-blob.yml
        input_mapping:
          artifact-release: consul-zip-release
          boshrelease-repo: repo-branched
        params:
          ARTIFACT_HUMAN_NAME:      Consul binary
          ARTIFACT_FILE_TEMPLATE:   consul_${artifact_version}_linux_amd64.zip
          BLOB_PATH_AWK_PATTERN:    consul\/consul_[0-9.]+_linux_amd64\.zip
          BLOB_PATH_TEMPLATE:       consul/consul_${artifact_version}_linux_amd64.zip
          PACKAGE_NAME:             consul
          ARTIFACT_REF_VARS_PREFIX: CONSUL

      - task: git-commit
        image: gk-ops-image
        file: gk-automation/tasks/git/commit.yml
        input_mapping:
          repo: boshrelease-repo-bumped
        params:
          GIT_COMMIT_NAME:  ((git-commit-name))
          GIT_COMMIT_EMAIL: ((git-commit-email))

      - task: upload-blobs
        image: gk-ops-image
        file: gk-automation/tasks/boshrelease/upload-blobs.yml
        input_mapping:
          boshrelease-repo: repo-committed
        params:
          S3_ACCESS_KEY_ID:     ((aws-access-key))
          S3_SECRET_ACCESS_KEY: ((aws-secret-key))

      - task: git-commit
        image: gk-ops-image
        file: gk-automation/tasks/git/commit.yml
        input_mapping:
          repo: boshrelease-repo-blobs-uploaded
        params:
          GIT_COMMIT_MESSAGE: "Uploaded blob for new Consul binary"
          GIT_COMMIT_NAME:    ((git-commit-name))
          GIT_COMMIT_EMAIL:   ((git-commit-email))

      - task: git-push
        image: gk-ops-image
        file: gk-automation/tasks/git/push-to-branch.yml
        input_mapping:
          repo: repo-committed
        params:
          GIT_URI:            ((consul_release_git_uri))
          GITHUB_PRIVATE_KEY: ((github-private-key))

      - task: compose-pr
        image: gk-ops-image
        file: gk-automation/tasks/boshrelease/compose-pr.yml
        params:
          ARTIFACT_HUMAN_NAME:    Consul
          RELEASE_NOTES_URL_TMPL: https://github.com/hashicorp/consul/blob/master/CHANGELOG.md

      - task: submit-pr
        image: gk-ops-image
        file: gk-automation/tasks/github/submit-pr.yml
        input_mapping:
          repo: repo-pushed
        params:
          GH_ACCESS_TOKEN: ((github-access-token))
          GH_OWNER:        gstackio
          GH_REPO:         gk-consul-boshrelease

  - name: detect-bpm
    serial: true
    serial_groups: [ detect ]
    plan:
      - in_parallel:
          - get: bpm-bosh-io-release
            trigger: true
            params: { tarball: false }
          - get: consul-boshrelease-master
          - get: gk-automation
          - get: gk-ops-image

      - task: bump-bpm
        image: gk-ops-image
        file: gk-automation/tasks/boshrelease/depl-manifest-release-bump.yml
        input_mapping:
          bosh-io-release: bpm-bosh-io-release
          repo:            consul-boshrelease-master
        params:
          RELEASE_NAME: bpm
          MANIFEST_PATH: deploy/gk-consul.yml

      - task: git-commit
        image: gk-ops-image
        file: gk-automation/tasks/git/commit.yml
        input_mapping:
          repo: repo-bumped
        params:
          GIT_COMMIT_NAME:  ((git-commit-name))
          GIT_COMMIT_EMAIL: ((git-commit-email))

      - put: consul-boshrelease-master
        params:
          repository: repo-committed
          rebase:     true
