---

resource_types:
  - name: keyval
    type: docker-image
    source:
      repository: swce/keyval-resource

  - name: hashicorp-release
    type: docker-image
    source:
      repository: starkandwayne/hashicorp-release-resource

resources:
  - name: gk-ops-image
    type: docker-image
    source:
      repository: gstack/gk-ops

  - name: consul-zip-release
    type: hashicorp-release
    source:
      project: consul

  - name: gk-automation
    type: git
    source:
      uri: git@github.com:gstackio/gk-automation.git
      branch: master
      private_key: ((github-private-key))

  - name: bpm-bosh-io-release
    type: bosh-io-release
    source:
      repository: cloudfoundry/bpm-release

  - name: consul-boshrelease-master
    type: git
    source:
      uri: ((consul_release_git_uri))
      branch: master
      private_key: ((github-private-key))

  - name: bump-info
    type: keyval

jobs:
  - name: detect
    plan:
      - in_parallel:
          - get: consul-zip-release
            trigger: true
            params: { regexp: linux_amd64.zip }
          - get: consul-boshrelease-master
          - get: gk-automation
          - get: gk-ops-image

      - task: add-blob
        input_mapping:
          consul-boshrelease: consul-boshrelease-master
        image: gk-ops-image
        config:
          platform: linux
          inputs:
            - name: consul-zip-release
            - name: consul-boshrelease
          outputs:
            - name: consul-boshrelease-bumped
            - name: bump-info
          run:
            path: /bin/bash
            args:
              - -exc
              - |
                find consul-zip-release -ls

                echo version: $(< consul-zip-release/version)
                echo project: $(< consul-zip-release/project)

                latest_consul_version=$(< consul-zip-release/version)

                git clone "consul-boshrelease" "consul-boshrelease-bumped"
                branch_name="bump-consul-${latest_consul_version}"

                pushd "consul-boshrelease-bumped" > /dev/null
                    git checkout "master"
                    git pull

                    if [[ ${branch_name} != "master" ]]; then
                        git checkout -b "${branch_name}"
                    fi

                    bosh blobs

                    old_consul_sha256=$(
                        bosh blobs --column path --column digest \
                        | awk '/consul\/consul_[0-9.]+_linux_amd64\.zip/{sub("^sha256:", "", $2); print $2}')
                    new_consul_sha256=$(
                        shasum -a 256 "../consul-zip-release/consul_${latest_consul_version}_linux_amd64.zip" \
                        | awk '{print $1}')
                    if [[ ${new_consul_sha256} == ${old_consul_sha256} ]]; then
                        echo "INFO: new blob has the same sha256 hash as the old one. Skipping blob update."
                    else
                        consul_old_blob_path=$(bosh blobs | awk '/consul\/consul_[0-9.]+_linux_amd64\.zip/{print $1}')

                        bosh remove-blob "${consul_old_blob_path}"
                        bosh add-blob "../consul-zip-release/consul_${latest_consul_version}_linux_amd64.zip" "consul/consul_${latest_consul_version}_linux_amd64.zip"

                        bosh blobs
                    fi

                    echo "Updating 'packages/consul/packaging' file."
                    sed -i -re "/CONSUL_VERSION=/s/=[0-9.]+\$/=${latest_consul_version}/" "packages/consul/packaging"
                    grep -F -nC 2 "CONSUL_VERSION=" "packages/consul/packaging"

                    echo "Updating 'scripts/add-blobs.sh' utility."
                    consul_sha256=$(bosh blobs --column path --column digest | awk '/consul\/consul_[0-9.]+_linux_amd64\.zip/{sub("^sha256:", "", $2); print $2}')
                    sed -i -re "/CONSUL_VERSION=/s/=[0-9.]+\$/=${latest_consul_version}/" "scripts/add-blobs.sh"
                    sed -i -re "/CONSUL_SHA256=/s/=[0-9a-f]+\$/=${consul_sha256}/" "scripts/add-blobs.sh"
                    grep -E -nC 2 "CONSUL_(VERSION|SHA256)=" "scripts/add-blobs.sh"

                    git config --global "color.ui" "always"
                    git status
                    git diff | cat

                    git config --global "user.name" "((git-commit-name))"
                    git config --global "user.email" "((git-commit-email))"

                    if [[ -z "$(git status --porcelain)" ]]; then
                        echo "INFO: nothing to commit. Skipping."
                    else
                        git add .
                        git commit -m "Bump consul binary to version ${latest_consul_version}"
                    fi
                popd > /dev/null


                # Write properties to the keyval output resource

                mkdir -p bump-info
                echo "latest_consul_version=${latest_consul_version}" >> bump-info/keyval.properties
                echo "branch_name=${branch_name}"                     >> bump-info/keyval.properties

      - put: bump-info
        params:
          file: bump-info/keyval.properties

      - task: upload-blobs
        params:
          S3_ACCESS_KEY_ID: ((aws-access-key))
          S3_SECRET_ACCESS_KEY: ((aws-secret-key))
        image: gk-ops-image
        config:
          platform: linux
          inputs:
            - name: consul-boshrelease-bumped
          outputs:
            - name: consul-boshrelease-blobs-uploaded
          params:
            S3_ACCESS_KEY_ID:
            S3_SECRET_ACCESS_KEY:
          run:
            path: /bin/bash
            args:
              - -exc
              - |
                git clone "consul-boshrelease-bumped" "consul-boshrelease-blobs-uploaded"
                cp -Rp "consul-boshrelease-bumped/blobs" "consul-boshrelease-blobs-uploaded"

                set +x
                cat <<EOF > "consul-boshrelease-blobs-uploaded/config/private.yml"
                ---
                blobstore:
                  options:
                    access_key_id: ${S3_ACCESS_KEY_ID}
                    secret_access_key: ${S3_SECRET_ACCESS_KEY}
                EOF
                set -x

                pushd "consul-boshrelease-blobs-uploaded" > /dev/null
                    bosh upload-blobs

                    git config --global "user.name" "((git-commit-name))"
                    git config --global "user.email" "((git-commit-email))"

                    git add "config/blobs.yml"
                    git commit -m "Uploaded blob for new Consul binary"
                popd > /dev/null

      - task: git-push
        image: gk-ops-image
        input_mapping:
          branch-info: bump-info
          repo: consul-boshrelease-blobs-uploaded
        params:
          GIT_URI: ((consul_release_git_uri))
          GITHUB_PRIVATE_KEY: ((github-private-key))
        file: gk-automation/boshrelease/git-push.yml

      - task: submit-pr
        params:
          GH_ACCESS_TOKEN: ((github-access-token))
          GH_OWNER: gstackio
          GH_REPO: gk-consul-boshrelease
        image: gk-ops-image
        config:
          platform: linux
          inputs:
            - name: bump-info
          params:
            GH_ACCESS_TOKEN:
            GH_OWNER:
            GH_REPO:
          run:
            path: /bin/bash
            args:
              - -exc
              - |
                grep -vE "^(UPDATED|UUID)=" "bump-info/keyval.properties" \
                    | sed -r -e 's/"/\"/g; s/=(.*)$/="\1"/' \
                    > keyval.inc.bash
                source "keyval.inc.bash"

                pr_desc="Hi there!"
                pr_desc+="\\n"
                pr_desc+="\\nI noticed that the new Consul v${latest_consul_version} is out,"
                pr_desc+=" so I suggest we update this BOSH Release with the latest binary available."
                pr_desc+="\\n"
                pr_desc+="\\nHere in this PR, I've pulled that new binary in."
                pr_desc+=" I uploaded the blob to the release blobstore, and here is the result."
                pr_desc+="\\n"
                pr_desc+="\\nDon't hesitate to have a look at the release notes: https://github.com/hashicorp/consul/blob/master/CHANGELOG.md"
                pr_desc+="\\nWhen it's okay to you, let's give it a shot, shall we?"
                pr_desc+="\\n"
                pr_desc+="\\nBest"

                # See also: https://developer.github.com/v3/pulls/#create-a-pull-request
                pr_data=$(jq -n \
                    --arg title "Bump Consul to version ${latest_consul_version}" \
                    --arg body "$(echo -e "${pr_desc}")" \
                    --arg head "${branch_name}" \
                    '{
                        "base": "master",
                        "title": $title,
                        "body": $body,
                        "head": $head,
                        "maintainer_can_modify": true
                    }')

                echo "Creating pull request: POST /repos/${GH_OWNER}/${GH_REPO}/pulls"
                # See also: https://developer.github.com/v3/
                curl --silent --fail \
                    --header "Accept: application/vnd.github.v3+json" \
                    --header "Authorization: token ${GH_ACCESS_TOKEN}" \
                    --request POST \
                    --url "https://api.github.com/repos/${GH_OWNER}/${GH_REPO}/pulls" \
                    --data-raw "${pr_data}"
                exit 0

  - name: detect-bpm
    serial: true
    serial_groups: [ detect ]
    plan:
      - in_parallel:
          - get: bpm-bosh-io-release
            trigger: true
            params: { tarball: false }
          - get: consul-boshrelease-master
          - get: gk-automation
          - get: gk-ops-image

      - task: bump-bpm
        image: gk-ops-image
        input_mapping:
          bosh-io-release: bpm-bosh-io-release
          repo: consul-boshrelease-master
        output_mapping:
          repo-bumped: consul-boshrelease-bumped
        file: gk-automation/boshrelease/depl-manifest-release-bump.yml
        params:
          RELEASE_NAME: bpm
          MANIFEST_PATH: deploy/gk-consul.yml
          GIT_EMAIL: ((git-commit-email))
          GIT_NAME: ((git-commit-name))

      - put: bump-info
        params:
          file: bump-info/keyval.properties

      - task: git-push
        image: gk-ops-image
        input_mapping:
          branch-info: bump-info
          repo: consul-boshrelease-bumped
        params:
          GIT_URI: ((consul_release_git_uri))
          GITHUB_PRIVATE_KEY: ((github-private-key))
        file: gk-automation/boshrelease/git-push.yml
