---
name: ((deployment_name))

instance_groups:
  - name: consul
    instances: 3
    azs: [ z1 ]
    jobs:
      - name: consul
        release: gk-consul
        provides:
          consul: { as: consul-servers }
          consul-address: { as: consul-server-address }
        consumes:
          consul-servers: { from: consul-servers }
        properties:
          server: true
          encrypt: ((consul_encrypt_key))
          tls:
            cert: ((consul_agent_tls))
            ca_bundle: |
              ((consul_clients_ca.certificate))
      - name: bpm
        release: bpm
    persistent_disk_type: default
    stemcell: default
    vm_type: default
    networks:
      - name: ((network_name))

  - name: consul-ui
    instances: 2
    azs: [ z1 ]
    jobs:
      - name: consul
        release: gk-consul
        provides:
          consul: { as: consul-ui-servers }
          consul-address: { as: consul-ui-address }
        consumes:
          consul-servers: { from: consul-servers }
        properties:
          server: true
          ui:
            enabled: true
          encrypt: ((consul_encrypt_key))
          tls:
            cert: ((consul_ui_tls))
            ca_bundle: |
              ((consul_clients_ca.certificate))
      - name: bpm
        release: bpm
    persistent_disk_type: default
    stemcell: default
    vm_type: default
    networks:
      - name: ((network_name))

  - name: smoke-tests-vm
    lifecycle: errand
    instances: 1
    azs: [ z1 ]
    jobs:
      - name: smoke-tests
        release: gk-consul
        consumes:
          consul-servers: { from: consul-servers }
        properties:
          client_cert: ((smoke_tests_client_cert))
          server_ca_bundle: |
            ((consul_ca.certificate))
    stemcell: default
    vm_type: default
    networks:
      - name: ((network_name))

variables:
  - name: consul_encrypt_key
    type: password
    options:
      length: 50
  - name: consul_ca
    type: certificate
    options:
      is_ca: true
      common_name: Consul CA
    update_mode: converge
  - name: consul_agent_tls
    type: certificate
    options:
      extended_key_usage: [ server_auth, client_auth ]
      ca: consul_ca
      common_name: consul.((network_name)).((deployment_name)).bosh
      alternative_names:
        - "*.consul.((network_name)).((deployment_name)).bosh"
        - "127.0.0.1"
        - "server.dc1.consul"
    consumes:
      alternative_name: { from: consul-server-address }
    update_mode: converge
  - name: consul_ui_tls
    type: certificate
    options:
      extended_key_usage: [ server_auth, client_auth ]
      ca: consul_ca
      common_name: consul-ui.((network_name)).((deployment_name)).bosh
      alternative_names:
        - "*.consul-ui.((network_name)).((deployment_name)).bosh"
        - "127.0.0.1"
        - "server.dc1.consul"
    consumes:
      alternative_name: { from: consul-ui-address }
    update_mode: converge
  - name: consul_clients_ca
    type: certificate
    options:
      is_ca: true
      common_name: Consul clients CA
    update_mode: converge
  - name: smoke_tests_client_cert
    type: certificate
    options:
      extended_key_usage: [ client_auth ]
      ca: consul_clients_ca
      common_name: smoke-tests
    update_mode: converge

features:
  use_dns_addresses: true

stemcells:
  - alias: default
    os: ubuntu-jammy
    version: latest

update:
  # NOTE: with 5 nodes, we can cope with 2 nodes being down at the same time,
  # so 'serial: false' is OK. But in production, 'serial: true' should be
  # considered for more safety.
  serial: false
  canaries: 1
  canary_watch_time: 1000-60000
  max_in_flight: 1
  update_watch_time: 1000-60000

releases:
- name: gk-consul
  sha1: d2f552d283406f1b72e2fe2e344b00ff7650b7c8
  stemcell:
    os: ubuntu-jammy
    version: "1.439"
  url: https://s3.eu-west-3.amazonaws.com/gk-consul-boshrelease/compiled-releases/gk-consul/gk-consul-1.7.0-ubuntu-jammy-1.439-20240510-144656-817884567-20240510144658.tgz
  version: 1.7.0
- name: bpm
  sha1: 93367b434f29493cc05cc960ca88d34c0a1d3e8d
  url: https://bosh.io/d/github.com/cloudfoundry/bpm-release?v=1.2.24
  version: 1.2.24
