---
name: ((deployment_name))

instance_groups:
  - name: consul
    instances: 3
    azs: [ z1 ]
    jobs:
      - name: consul
        release: gk-consul
        provides:
          consul: { as: consul-servers }
          consul-address: { as: consul-server-address }
        consumes:
          consul-servers: { from: consul-servers }
        properties:
          server: true
          encrypt: ((consul_encrypt_key))
          tls:
            cert: ((consul_agent_tls))
      - name: bpm
        release: bpm
    persistent_disk_type: default
    stemcell: default
    vm_type: default
    networks:
      - name: ((network_name))

  - name: consul-ui
    instances: 2
    azs: [ z1 ]
    jobs:
      - name: consul
        release: gk-consul
        provides:
          consul-address: { as: consul-ui-address }
        consumes:
          consul-servers: { from: consul-servers }
        properties:
          server: true
          ui:
            enabled: true
          encrypt: ((consul_encrypt_key))
          tls:
            cert: ((consul_ui_tls))
      - name: bpm
        release: bpm
    persistent_disk_type: default
    stemcell: default
    vm_type: default
    networks:
      - name: ((network_name))

variables:
  - name: consul_encrypt_key
    type: password
    options:
      length: 50
  - name: consul_ca
    type: certificate
    options:
      is_ca: true
      common_name: Consul CA
  - name: consul_agent_tls
    type: certificate
    options:
      ca: consul_ca
      common_name: consul.((network_name)).((deployment_name)).bosh
      alternative_names:
        - "*.consul.((network_name)).((deployment_name)).bosh"
        - "127.0.0.1"
        - "server.dc1.consul"
    consumes:
      alternative_name: { from: consul-server-address }
    update_mode: converge
  - name: consul_ui_tls
    type: certificate
    options:
      ca: consul_ca
      common_name: consul-ui.((network_name)).((deployment_name)).bosh
      alternative_names:
        - "*.consul-ui.((network_name)).((deployment_name)).bosh"
        - "127.0.0.1"
        - "server.dc1.consul"
    consumes:
      alternative_name: { from: consul-ui-address }
    update_mode: converge

features:
  use_dns_addresses: true

stemcells:
  - alias: default
    os: ubuntu-xenial
    version: latest

update:
  # NOTE: with 5 nodes, we can cope with 2 nodes being down at the same time,
  # so 'serial: false' is OK. But in production, 'serial: true' should be
  # considered for more safety.
  serial: false
  canaries: 1
  canary_watch_time: 1000-60000
  max_in_flight: 1
  update_watch_time: 1000-60000

releases:
- name: gk-consul
  version: latest
- name: bpm
  sha1: e612e88543012ae5d376dd3746159d5abe748076
  url: https://bosh.io/d/github.com/cloudfoundry/bpm-release?v=1.1.5
  version: 1.1.5
