---
meta:
  name:    gk-consul
  release: Consul BOSH Release
  target:  gk-plat-devs
  url:     https://ci.gstack.io
  team:    gk-plat-devs

  test-errands: smoke-tests

  initial_version: "1.0.0"

  manifest:
    directory: deploy
    vars: |
      ---
      deployment_name: gk-consul-testflight
      network_name: default
    vars-pr: |
      ---
      deployment_name: gk-consul-testflight-pr
      network_name: default

  git:
    email:  ((git-commit-email))
    name:   ((git-commit-name))

  image:
    name: harbor.ci.gstack.io/gstack/gk-ops
    registry:
      username: ((docker-registry-username))
      password: ((docker-registry-password))

  aws:
    bucket:      (( grab meta.pipeline ))
    region_name: eu-west-3
    access_key:  ((aws-access-key))
    secret_key:  ((aws-secret-key))

  github:
    owner:  gstackio
    repo:   (( grab meta.pipeline ))
    branch: master
    private_key:  ((github-private-key))
    access_token: ((github-access-token))

  bosh:
    stemcell:
      cpi: warden-boshlite

  slack:
    webhook:       ((slack-webhook))
    username:      ((slack-username))
    channel:       oss-pipelines-notifications



resources:

  - name: git
    check_every: 24h
    webhook_token: ((concourse-webhook-token))

  - name: git-pull-requests
    check_every: 24h
    webhook_token: ((concourse-webhook-token))
